### ISSUE TITLE
no response when creating a class object Client

### ISSUE THREAD

**Issue by Ankalim** [ClickHouse/clickhouse-cpp#165]
Hi!
I tried run example code. My code show like this:

`#include <clickhouse/client.h>
#include <iostream>
using namespace clickhouse;

int main(){
    /// Initialize client connection.
    ClientOptions settings = ClientOptions();
    settings.SetHost("111.111.11.11");
    settings.SetPort(8123);
    settings.SetUser("default");
    settings.SetPassword("****");
    
    Client client(settings);
    std::cout << "check 1";
    client.Ping();
    std::cout << "check 2";
    client.Select("SELECT clo1, col2 from table", [] (const Block& block)
        {
            for (size_t i = 0; i < block.GetRowCount(); ++i) {
                std::cout << block[0]->As<ColumnString>()->At(i) << " "
                        << block[1]->As<ColumnString>()->At(i) << "\n";
            }
        }
    );
    
    return 0;
}`

My code runs to the line
` Client client(settings);`
Nothing happens after that, but the program does not throw exceptions

in debug  with GDB I get this backtrace:
`
#0  0x00007ffff7c3b470 in __libc_recv (fd=3, buf=0x555555572260, len=8192, flags=0)
    at ../sysdeps/unix/sysv/linux/recv.c:28
#1  0x00007ffff7f42cc6 in clickhouse::SocketInput::DoRead(void*, unsigned long) ()
   from /usr/local/lib/libclickhouse-cpp-lib.so
#2  0x00007ffff7f421ca in clickhouse::BufferedInput::DoRead(void*, unsigned long) ()
   from /usr/local/lib/libclickhouse-cpp-lib.so
#3  0x00007ffff7f444ff in clickhouse::WireFormat::ReadVarint64(clickhouse::InputStream&, unsigned long*) ()
   from /usr/local/lib/libclickhouse-cpp-lib.so
#4  0x00007ffff7f76fcc in clickhouse::Client::Impl::ReceiveHello() () from /usr/local/lib/libclickhouse-cpp-lib.so
#5  0x00007ffff7f7727c in clickhouse::Client::Impl::ResetConnection() () from /usr/local/lib/libclickhouse-cpp-lib.so
#6  0x00007ffff7f77c22 in clickhouse::Client::Impl::Impl(clickhouse::ClientOptions const&, std::unique_ptr<clickhouse::SocketFactory, std::default_delete<clickhouse::SocketFactory> >) () from /usr/local/lib/libclickhouse-cpp-lib.so
#7  0x00007ffff7f77cbb in clickhouse::Client::Impl::Impl(clickhouse::ClientOptions const&) ()
   from /usr/local/lib/libclickhouse-cpp-lib.so
#8  0x00007ffff7f77d2c in clickhouse::Client::Client(clickhouse::ClientOptions const&) ()
   from /usr/local/lib/libclickhouse-cpp-lib.so
#9  0x0000555555556969 in main () at run.cpp:15
`

my compiling command if You need it
`g++ -Wall run.cpp -std=c++17 -g -c  -o result.o -lclickhouse-cpp-lib -L/usr/local/lib -g`

my system params:
Operating System: Ubuntu 20.04.3 LTS
Kernel: Linux 5.13.0-30-generic
Architecture: x86-64

Thank you very much!

**Comment by Ankalim** [comment]
I find problem.
I set port 8123 like http interface. But for it need port default 9000 - tcp.
